<a href="https://colab.research.google.com/github/ferreirabruno7/machine_learning/blob/master/tensor_flow_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#acessar google drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [4]:
#importação das biblicates de apoio
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf

%matplotlib inline
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot
init_notebook_mode(connected=True)
import datetime

In [0]:


#carregar dados de treino
emendas = pd.read_csv("/content/drive/My Drive/Colab Notebooks/emendas_parlamentares_2.csv", delimiter = ',', encoding='utf-8', decimal='.')


In [0]:
emendas[".liquidado"] = [x.replace(",", ".") for x in emendas[".liquidado"]]
emendas['.liquidado'] = emendas['.liquidado'].astype(float)
emendas['.empenho'] = emendas['.empenho'].astype(float)

In [9]:
emendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4184 entries, 0 to 4183
Data columns (total 25 columns):
.despesa_autorizada                4184 non-null int64
.empenho                           4184 non-null float64
.liquidado                         4184 non-null float64
.total                             4184 non-null int64
.valor_medio_destinado             4184 non-null int64
% de empenho                       2390 non-null float64
ano                                4184 non-null int64
atuacao                            4184 non-null object
Média de Autorizado x Empenhado    2390 non-null float64
Categoria Econômica                4184 non-null object
classe                             4184 non-null object
Elemento de Despesa                4184 non-null object
Fonte de Recurso                   4184 non-null object
Função                             4184 non-null object
Gestão                             4184 non-null object
Grupo de Natureza da Despesa       4184 non-null obje

In [0]:

emendas['.empenho'].fillna(value=emendas['.empenho'].median(), inplace=True)
emendas['.despesa_autorizada'].fillna(value=emendas['.despesa_autorizada'].median(), inplace=True)
emendas['Média de Autorizado x Empenhado'].fillna(value=emendas['Média de Autorizado x Empenhado'].median(), inplace=True)
emendas['Média de Autorizado x Empenhado'].fillna(value=emendas['Média de Autorizado x Empenhado'].median(), inplace=True)
emendas["execucao"]= emendas[".empenho"].div(other = emendas['.despesa_autorizada'], fill_value = 0) 


In [0]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
classe_new = le.fit(emendas['classe'])
novas = le.transform(emendas['classe'])
emendas['classe_new'] = le.transform(emendas['classe'])


In [29]:
emendas['classe_new'].value_counts()

1    3178
0     959
2      47
Name: classe_new, dtype: int64

In [11]:
emendas.describe()

.despesa_autorizada  ...  execucao
count         4.184000e+03  ...   3145.00
mean          4.167068e+05  ...       inf
std           1.091213e+06  ...       NaN
min           0.000000e+00  ...      0.00
25%           0.000000e+00  ...      0.00
50%           1.000000e+05  ...      0.00
75%           4.000000e+05  ...      1.05
max           1.911194e+07  ...       inf

[8 rows x 9 columns]

In [111]:
X = emendas[[
    
    
    '.despesa_autorizada',
    '.empenho',
    '.valor_medio_destinado'
   
]]

X

.despesa_autorizada    .empenho  .valor_medio_destinado
0                  200000        0.00                  200000
1                  100000        0.00                  100000
2                  100000        0.00                  100000
3                  100000        0.00                  100000
4                   67000        0.00                   67000
5                  117000        0.00                  117000
6                  503000        0.00                  503000
7                       0        0.00                       0
8                       0  7185000.00                       0
9                       0        0.00                       0
10                      0  8700000.00                       0
11                      0        0.00                       0
12                      0  6459000.00                       0
13                      0        0.00                       0
14                  24000        0.00                   24000
15                  26000        0.00                   26000
16                 100000        0.00                  100000
17                 280000        0.00                  280000
18                 700000        0.00                  700000
19                      0   700000.00                       0
20                      0   200000.00                       0
21                 400000        0.00                  400000
22                      0   283242.00                       0
23                1000000   324000.00                 1000000
24                      0   150000.00                       0
25                 150000        0.00                  150000
26                1000000        0.00                 1000000
27                 750000   150000.00                  750000
28                      0  1380398.58                       0
29                  50000        0.00                   50000
...                   ...         ...                     ...
4154                    0        0.00                       0
4155                    0        0.00                       0
4156                    0        0.00                       0
4157                    0        0.00                       0
4158                    0        0.00                       0
4159                    0        0.00                       0
4160                    0        0.00                       0
4161                    0        0.00                       0
4162                    0        0.00                       0
4163                    0        0.00                       0
4164                    0        0.00                       0
4165                    0        0.00                       0
4166                    0        0.00                       0
4167                    0        0.00                       0
4168                    0        0.00                       0
4169                    0        0.00                       0
4170                    0        0.00                       0
4171                    0        0.00                       0
4172                    0        0.00                       0
4173                    0        0.00                       0
4174                    0        0.00                       0
4175                    0        0.00                       0
4176               111940        0.00                  111940
4177                    0        0.00                       0
4178                    0        0.00                       0
4179                    0        0.00                       0
4180               100000        0.00                  100000
4181               100000        0.00                  100000
4182                80000        0.00                   80000
4183               200000        0.00                  200000

[4184 rows x 3 columns]

In [112]:
y = emendas['classe_new']
y

0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       0
9       1
10      0
11      1
12      0
13      1
14      1
15      1
16      1
17      1
18      1
19      0
20      0
21      1
22      0
23      1
24      0
25      1
26      1
27      0
28      0
29      1
       ..
4154    1
4155    1
4156    1
4157    1
4158    1
4159    1
4160    1
4161    1
4162    1
4163    1
4164    1
4165    1
4166    1
4167    1
4168    1
4169    1
4170    1
4171    1
4172    1
4173    1
4174    1
4175    1
4176    1
4177    1
4178    1
4179    1
4180    1
4181    1
4182    1
4183    1
Name: classe_new, Length: 4184, dtype: int64

In [113]:
#padronização dos dados
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-0.19861638, -0.21569132, -0.19842573],
       [-0.2902685 , -0.21569132, -0.29010482],
       [-0.2902685 , -0.21569132, -0.29010482],
       ...,
       [-0.2902685 , -0.21569132, -0.29010482],
       [-0.30859893, -0.21569132, -0.30844064],
       [-0.19861638, -0.21569132, -0.19842573]])

In [114]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(categorical_features = [0])
y.shape


(4184,)

In [115]:
y = y.values.reshape(-1,1)
y.shape

(4184, 1)

In [116]:
y = onehot.fit_transform(y).toarray()
y

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning:

The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning:

The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.



array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [0]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [118]:
X_treinamento.shape

(2928, 3)

In [119]:
X_teste.shape

(1256, 3)

In [120]:
neuronios_entrada = X.shape[1]
neuronios_entrada

3

In [121]:
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1])/2))
neuronios_oculta

3

In [122]:
neuronios_saida = y.shape[1]
neuronios_saida

3

In [0]:
W = {'oculta' : tf.Variable(tf.random_normal([neuronios_entrada, neuronios_oculta])), 'saida':  tf.Variable(tf.random_normal([neuronios_oculta, neuronios_saida]))}

In [0]:
b = {'oculta' : tf.Variable(tf.random_normal([neuronios_oculta])), 'saida' : tf.Variable(tf.random_normal([neuronios_saida]))}

In [0]:
xph = tf.placeholder('float', [None, neuronios_entrada])
yph = tf.placeholder('float', [None, neuronios_saida])

In [0]:
def mlp(x, W, bias):
  camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta'])
  camada_oculta_ativacao = tf.nn.relu(camada_oculta)
  camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
  return camada_saida

In [0]:
modelo = mlp(xph, W, b)

In [0]:
erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits = modelo, labels = yph))
otimizador = tf.train.AdamOptimizer(learning_rate = 0.0001).minimize(erro)

In [129]:
batch_size = 8
batch_total = int(len(X_treinamento) / batch_size)

batch_total

366

In [130]:
X_batches = np.array_split(X_treinamento, batch_total)
X_batches

[array([[ 0.53460059, -0.21569132,  0.53500697],
        [-0.38192063, -0.05448   , -0.38178391],
        [-0.15279032, -0.21569132, -0.15258619],
        [-0.38192063,  0.34693618, -0.38178391],
        [ 0.07633998, -0.21569132,  0.07661153],
        [-0.38192063, -0.21569132, -0.38178391],
        [ 0.53460059, -0.21569132,  0.53500697],
        [-0.35992412, -0.21569132, -0.35978093]]),
 array([[-0.38192063, -0.21569132, -0.38178391],
        [-0.38192063, -0.21569132, -0.38178391],
        [-0.38192063, -0.21569132, -0.38178391],
        [-0.08536002,  1.3947464 , -0.08513605],
        [-0.19861638, -0.21569132, -0.19842573],
        [ 0.53460059, -0.21569132,  0.53500697],
        [-0.38192063, -0.07642119, -0.38178391],
        [-0.38192063, -0.21569132, -0.38178391]]),
 array([[-0.38192063, -0.11896453, -0.38178391],
        [-0.2100729 , -0.21569132, -0.20988562],
        [-0.24444244, -0.21569132, -0.24426528],
        [ 1.4511218 , -0.21569132,  1.45179785],
        [ 0.0763

In [131]:
X_batches[1]

array([[-0.38192063, -0.21569132, -0.38178391],
       [-0.38192063, -0.21569132, -0.38178391],
       [-0.38192063, -0.21569132, -0.38178391],
       [-0.08536002,  1.3947464 , -0.08513605],
       [-0.19861638, -0.21569132, -0.19842573],
       [ 0.53460059, -0.21569132,  0.53500697],
       [-0.38192063, -0.07642119, -0.38178391],
       [-0.38192063, -0.21569132, -0.38178391]])

In [0]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for epoca in range(3000):
    erro_medio = 0.0
    batch_total = int(len(X_treinamento)/batch_size)
    X_batches = np.array_split(X_treinamento, batch_total)
    y_batches = np.array_split(y_treinamento, batch_total)
    for i in range(batch_total):
      X_batch, y_batch = X_batches[i], y_batches[i]
      _, custo = sess.run([otimizador, erro], feed_dict = {xph: X_batch, yph: y_batch})
      erro_medio += custo/batch_total
    if epoca % 500 == 0:
      print('Época ' + str((epoca + 1)) + ' erro: ' + str(erro_medio))
    
    W_final, b_final = sess.run([W, b])

Época 1 erro: 4.2996689058392406


In [102]:
W_final

{'oculta': array([[-4.929951  , -1.5381559 , -1.4220128 ],
        [-0.47146896, -1.6243181 ,  1.629394  ]], dtype=float32),
 'saida': array([[ 1.6505744 , -2.7036417 , -0.01533927],
        [-0.01656152,  2.1752417 ,  0.8090444 ],
        [-0.55999845,  0.34679577, -0.85277873]], dtype=float32)}

In [103]:
b_final

{'oculta': array([-1.0235499 ,  0.02010404,  0.82344526], dtype=float32),
 'saida': array([ 0.300774 ,  1.0368065, -2.0163093], dtype=float32)}

In [0]:
#previsões

previsoes_teste = mlp(xph, W_final, b_final)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  rl = sess.run(previsoes_teste, feed_dict = {xph : X_teste})
  r2 = sess.run(tf.nn.softmax(rl))
  r3 = sess.run(tf.argmax(r2, 1))

In [105]:
rl

array([[ 1.2955174 , -0.02819717,  1.5848572 ],
       [ 0.7748562 ,  3.5762324 ,  2.983901  ],
       [-1.6266819 ,  0.0995867 , -1.9681649 ],
       ...,
       [-0.17437959, -0.34213632,  0.93173605],
       [ 2.2617795 ,  1.7463136 ,  3.1981497 ],
       [ 0.9602791 ,  0.40668327,  1.5868666 ]], dtype=float32)

In [106]:
r2

array([[0.3843655 , 0.1022969 , 0.5133376 ],
       [0.03763033, 0.61966974, 0.34269994],
       [0.13641892, 0.766626  , 0.09695504],
       ...,
       [0.20541668, 0.17369202, 0.62089133],
       [0.2410842 , 0.14398086, 0.6149349 ],
       [0.2901837 , 0.16682048, 0.5429958 ]], dtype=float32)

In [107]:
r3

array([2, 1, 1, ..., 2, 2, 2])

In [108]:
y_teste2 = np.argmax(y_teste, 1)
y_teste2

array([1, 1, 1, ..., 2, 0, 1])

In [0]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, r3)

In [110]:
taxa_acerto

0.571656050955414